// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnJV-KYmmHwera5fOZqRVYymgiOrS9uAk',
    appId: '1:739089643859:web:6c772588a06d3352dac9a6',
    messagingSenderId: '739089643859',
    projectId: 'swfact-summer-mini-project',
    authDomain: 'swfact-summer-mini-project.firebaseapp.com',
    storageBucket: 'swfact-summer-mini-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXU3EBMp5YEU3o-1YyauanwJY4_Kec4wE',
    appId: '1:739089643859:android:4672c1027b3e5cd0dac9a6',
    messagingSenderId: '739089643859',
    projectId: 'swfact-summer-mini-project',
    storageBucket: 'swfact-summer-mini-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOfDxH_6nh9WJm1OuN06DhtJ_pa72V4zo',
    appId: '1:739089643859:ios:e542eda04d2fb30adac9a6',
    messagingSenderId: '739089643859',
    projectId: 'swfact-summer-mini-project',
    storageBucket: 'swfact-summer-mini-project.appspot.com',
    iosClientId: '739089643859-0s9qamlii2aqnc68o47ct2v53foq3mq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flameGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOfDxH_6nh9WJm1OuN06DhtJ_pa72V4zo',
    appId: '1:739089643859:ios:e542eda04d2fb30adac9a6',
    messagingSenderId: '739089643859',
    projectId: 'swfact-summer-mini-project',
    storageBucket: 'swfact-summer-mini-project.appspot.com',
    iosClientId: '739089643859-0s9qamlii2aqnc68o47ct2v53foq3mq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flameGame',
  );
}
